var dataSet = [
    
// A ---------------------------------------------------------------------------
    ["Aizicovici", 
     "Sergiu", 
     "Professor", 
     "Mathematics", 
     "$134,567.00"],
    
    ["Allen", 
     "Neeley", 
     "Coordinator of Communications & Marketing", 
     "Chillicothe Public Relations", 
     "$44,081.00"],
    
    ["Allen", 
     "Jeff	", 
     "N/A", 
     "Marketing", 
     "$85,850.00"],
    
    ["Alloway", 
     "Laura", 
     "Director of Marketing and Communications", 
     "Voinovich Schl of Leadership & Public Affairs", 
     "$91,834.00"],
    
    ["Amand", 
     "Clinton", 
     "Assistant Director, Multimedia Content", 
     "Advancement Services", 
     "$55,550.00"],
    
    ["Anderson", 
     "Nathan", 
     "Assistant Director, Annual Giving", 
     "Advancement Services", 
     "$46,436.00"],
    
    ["Anderson", 
     "Denissa", 
     "N/A", 
     "English", 
     "$62,386.00"],
    
    ["Andrews", 
     "James", 
     "Associate Professor", 
     "Classics and World Religions", 
     "$87,279.00"],
    
    ["Atwood", 
     "Joyce", 
     "Resource Development Director", 
     "Chillicothe Dean's Office", 
     "$68,810.56"],
    
// B ---------------------------------------------------------------------------
    ["Babrow",	
     "Austin",	
     "Professor",	
     "School of Communication Studies",	
     "$114,476.00"],
    
    ["Bach",	
     "Morten",	
     "N/A",	
     "History",	
     "$49,847.00"],
    
    ["Backes",	
     "Elizabeth",	
     "Assistant Director of Marketing",	
     "Health Sciences Professions, Dean's Office",	
     "$66,674.00"],
    
    ["Bailes",	
     "April",	
     "Administrative Services Associate",	
     "Mathematics",	
     "$30,784.00"],
    
    ["Baird",	
     "Timothy",	
     "International Admissions Advisor",	
     "Admissions",	
     "$40,925.00"],
    
    ["Baker",	
     "Brandi",	
     "Assistant Director, Multicultural Affairs",	
     "COM-Dean's Office",	
     "$58,270.00"],
    
    ["Barlag",	
     "Kimberly",	
     "Director of Communications & Marketing",	
     "Curriculum and Technology Center",	
     "$67,900.00"],
    
    ["Barnett",	
     "Beth A Mcclure",	
     "N/A",	
     "Nursing",	
     "$51,128.00"],
    
    ["Bauer",	
     "Lori",	
     "Senior Director of Communications & Marketing",	
     "Arts and Sciences, Dean's Office",	
     "$96,143.00"],
    
    ["Baumgartel",	
     "Rudiger",	
     "Grounds Services Manager",	
     "Grounds-Grounds Maintenance",	
     "$55,565.00"],
    
    ["Baur",	
     "Bryan",	
     "Administrative Specialist",	
     "Classics and World Religions",	
     "$35,401.60"],
    
    ["Baxstrom",	
     "Emily",	
     "Communications Specialist",	
     "INSTRUCTIONAL INNOVATION",	
     "$42,929.00"],
    
    ["Bayless",	
     "David",	
     "Professor",	
     "Mechanical Engineering",	
     "$215,265.00"],
    
    ["Beasecker",	
     "Caleb",	
     "Associate Director of the Ohio Bobcat Club",	
     "Intercollegiate Athletics Office",	
     "$54,000.00"],
    
    ["Becker",	
     "Janet",	
     "Associate Professor",	
     "Associate Dean - Lancaster",	
     "$113,500.00"],
    
    ["Benedicto",	
     "Eunice",	
     "Manager, General Accounting & Financial Reporting",	
     "General Accounting",	
     "$76,886.00"],
    
    ["Bennett",	
     "Ann",	
     "Department Administrator",	
     "Sociology and Anthropology",	
     "$52,643.00"],
    
    ["Bennett-Hanning",	
     "Jacqueline",	
     "Administrative Specialist",	
     "Chemistry and Biochemistry",	
     "$49,628.80"],
    
    ["Bentley",	
     "Danny",	
     "N/A",	
     "Biological Sciences",	
     "$14,337.00"],
    
    ["Berry",	
     "Kris",	
     "University Custodial Services Manager",	
     "Custodial Services - Administration",	
     "$48,079.00"],
    
    ["Binegar",	
     "Timothy",	
     "Senior Director of Development, Patton College of Education",	
     "Development",	
     "$107,623.00"],
    
    ["Bingham",	
     "Douglas",	
     "Custodial Worker",	
     "Pickerington Center-Lancaster",	
     "$26,104.00"],
    
    ["Blake",	
     "Timothy",	
     "Assoc Professor",	
     "Nursing-Zanesville",	
     "$78,699.00"],
    
    ["Blower",	
     "Scott",	
     "Grounds Services Manager",	
     "Grounds-Grounds Maintenance",	
     "$64,327.00"],
    
    ["Bradshaw",	
     "Marilyn",	
     "Professor",	
     "Art",	
     "$92,535.00"],
    
    ["Bragg",	
     "Christine",	
     "Administrative Services Assistant",	
     "Culinary Services",	
     "$23,649.60"],
    
    ["Branham",	
     "Bryan",	
     "Associate Professor",	
     "Aviation",	
     "$103,253.00"],
    
    ["Bricker",	
     "Richard",	
     "Associate Director, Facilities & Operations",	
     "Ping Recreation Center",	
     "$64,584.00"],
    
    ["Brooks",	
     "Karen",	
     "Key Shop Manager",	
     "Facilities Management",	
     "$59,459.00"],
    
    ["Brown",	
     "Jeffrey",	
     "Communication Designer",	
     "COM-Communication",	
     "$55,137.00"],
    
    ["Bulow",	
     "Megan",	
     "Director of Communications for OII",	
     "INSTRUCTIONAL INNOVATION",	
     "$71,206.00"],
    
    ["Bunescu",	
     "Constantin",	
     "Professor",	
     "Electrical Engineering and Computer Science",	
     "$117,387.00"],
    
    ["Burcham",	
     "Stephanie",	
     "Director, Proctorville Center",	
     "Director Proctorville",	
     "$78,057.00"],
    
    ["Burmeister",	
     "Larry",	
     "Professor",	
     "Sociology and Anthropology",	
     "$98,000.00"],
    
    ["Burroway",	
     "Sarah E Diamond",	
     "Director of External Relations",	
     "Southern Campus Dean's Office",	
     "$74,999.00"],
    
// C ---------------------------------------------------------------------------    
    ["Cabrera",	
     "Margaret",	
     "Administrtive Services Associate",	
     "Community Standards & Student Responsibility",	
     "$34,860.80"],
    
    ["Callahan",	
     "Robert",	
     "Acting Senior Director, Recruitment and Partnerships",	
     "Admissions",	
     "$94,710.00"],
    
    ["Campbell",	
     "Jennifer",	
     "Financial Information Manager",	
     "Accounts Payable",	
     "$57,370.00"],
    
    ["Cao",	
     "Qiuping",	
     "Assoc Professor, Early Childhood Education",	
     "Education-Lancaster",	
     "$89,263.00"],
    
    ["Carlson",	
     "Bruce",	
     "Associate Professor",	
     "Psychology",	
     "$139,018.00"],
    
    ["Carow",	
     "Colleen",	
     "Senior Director of Communications",	
     "Engineering and Technology, Dean's Office",	
     "$109,122.00"],
    
    ["Carpenter",	
     "John",	
     "University Custodial Services Manager",	
     "Custodial Services - Administration",	
     "$58,683.00"],
    
    ["Carr",	
     "Tyrone",	
     "Special Assistant to the Vice President for University Advancement/Executive Director of Interlink Alliance",	
     "VP University Advancement",	
     "$97,756.00"],
    
    ["Cartwright",	
     "Bryce",	
     "Assistant Director of Scholarship Management",	
     "Student Financial Aid",	
     "$39,506.00"],
    
    ["Casto",	
     "Joshua",	
     "Director of Marketing and Communications",	
     "Business, Dean's Office",	
     "$93,287.00"],
    
    ["Celenk",	
     "Mehmet",	
     "Professor",	
     "Electrical Engineering and Computer Science",	
     "$100,570.00"],
    
    ["Chiasson",	
     "Wayne",	
     "Department Administrator",	
     "Physics and Astronomy",	
     "$77,389.00"],
    
    ["Childers",	
     "Carla",	
     "Associate Professor of Marketing",	
     "Marketing",	
     "$131,930.00"],
    
    ["Chleboun",	
     "Gary",	
     "Professor",	
     "Physical Therapy",	
     "$180,795.00"],
    
    ["Cochran",	
     "Jennifer",	
     "Director of Strategic Communication and External Relations",	
     "University College, Dean's Office",	
     "$48,095.00"],
    
    ["Cohen",	
     "Lisa",	
     "Senior Director of External Relations, College of Arts & Sciences",	
     "Arts and Sciences, Dean's Office",	
     "$78,163.00"],
    
    ["Collins",	
     "Megan",	
     "Administrative Specialist",	
     "Provost Office",	
     "$36,400.00"],
    
    ["Collins",	
     "Peter",	
     "Assistant Director, Ohio Bobcat Club",	
     "ICA Development",	
     "$40,400.00"],
    
    ["Collins",	
     "Rebecca",	
     "N/A",	
     "SOAN",	
     "$68,651.00"],
    
    ["Colloredo",	
     "Francesca",	
     "N/A",	
     "MODL",	
     "$65,544.00"],
    
    ["Condee",	
     "William",	
     "Professor",	
     "School of Interdisciplinary Arts",	
     "$114,369.00"],
    
    ["Conner",	
     "Brandt",	
     "N/A",	
     "Marketing",	
     "$73,968.00"],
    
    ["Cottrell",	
     "Colin",	
     "Administrative Specialist",	
     "INSTRUCTIONAL INNOVATION",	
     "$38,875.20"],
    
    ["Cribben",	
     "Denise",	
     "Administrative Services Associate",	
     "Electrical Engineering and Computer Science",	
     "$37,294.40"],
    
    ["Crockett",	
     "Elizabeth",	
     "Professor",	
     "Biological Sciences",	
     "$102,638.00"],
    
    ["Cromwell",	
     "Arthur",	
     "Assoc Professor",	
     "Schl of Media Arts & Studies",	
     "$81,769.00"],
    
    ["Crowl",	
     "Samuel",	
     "Associate Director of Sustainability",	
     "Facilities Management",	
     "$52,309.00"],
    
    ["Cullums",	
     "Ronald",	
     "Manager, Community and Corporate Learning",	
     "Cont Education-Lancaster",	
     "$55,320.00"],
    
// D ---------------------------------------------------------------------------
    ["Datsenko"	,
    "Ella"	,
    "N/A"	,
    "OPIE"	,
    "$66,639.00"],

    ["De Oliveira"	,
    "Ruben"	,
    "Business Intelligence Developer III",	
    "Information Technology - WUSOC	",
    "$85,112.00"],

    ["Deguchi"	,
    "Ayako	",
    "N/A	",
    "LING	",
    "$67,140.00"],

    ["Delaney"	,
    "Dennis	",
    "Assoc Professor	",
    "Theater	",
    "$69,471.00"],

    ["Delaney"	,
    "Shelley"	,
    "Professor	",
    "Theater	",
    "$83,647.00"],

    ["Delaval	",
    "Molly	",
    "Department Administrator, Mathematics	",
    "Mathematics	",
    "$49,891.00"],

    ["DeWees	",
    "Amanda	",
    "Senior Director of Development, Scripps College of Communication	",
    "Development	",
    "$106,000.00"],

    ["Dewey	",
    "Jamie	",
    "Administrative Specialist	",
    "Biological Sciences	",
    "$39,520.00"],

    ["Dick",
    "Lauren	",
    "Grants Development and Performance Coordinator	",
    "Nursing - Athens	",
    "$54,899.00"],

    ["Dillon	",
    "Aaron	",
    "Procurement Specialist	",
    "Chemistry and Biochemistry	",
    "$34,715.20"],

    ["Dishong	",
    "Candace	",
    "Administrative Specialist	",
    "Physics and Astronomy	",
    "$38,937.60"],

    ["Donley	",
    "Linda	",
    "Administrative Services Associate	",
    "Housing & Residence Life	",
    "$36,587.20"],

    ["Dorcena	",
    "Cassandre Jeanny	",
    "N/A	",
    "Dean's Office	",
    "$75,000.00"],

    ["Doty	",
    "Sandra	",
    "Assoc Professor of Physics	",
    "Arts and Sciences-Lancaster	",
    "$77,819.00"],

    ["Dovbnya"	,
    "Tatjana"	,
    "N/A"	,
    "MODL"	,
    "$67,446.00"],

    ["Downard	",
    "Susan	",
    "Senior Director of Development, College of Arts & Sciences	",
    "Arts and Sciences, Dean's Office	",
    "$115,171.00"],

    ["Dragiev"	,
    "Kiril	",
    "N/A	",
    "OPIE	",
    "$64,826.00"],

    ["Dunfee	",
    "Kara	",
    "Administrative Specialist	",
    "Contemporary History Institute	",
    "$48,547.20"],

    ["Dupler",
     "David	",
    "Network Administrator, Senior Specialist	",
    "Network Operations	",
    "$65,041.60"],

// E ---------------------------------------------------------------------------
    ["Edmonds	",
    "Lorna Jean	",
    "Professor	",
    "Provost Office	",
    "$207,511.00"],

    ["Edwards	",
    "Heather	",
    "N/A	",
    "ENGL	",
    "$82,908.00"],

    ["Ehrlich	",
    "Philip	",
    "Professor	",
    "Philosophy	",
    "$102,402.00"],

    ["Ellinger	",
    "Thomas	",
    "Manager of Communications and Marketing	",
    "Lancaster Dean's Office	",
    "$57,696.00"],

    ["Erlewine	",
    "Kathleen	",
    "Director, Digital Communication"	,
    "University Advancement/Computer Operations	",
    "$67,260.00"],
    
// F ---------------------------------------------------------------------------
    ["Facun	",
    "Richard	",
    "Photographic Resources Supervisor	",
    "COM-Communication	",
    "$59,310.00"],

    ["Fairchild	",
    "James	",
    "Creative Design Specialist	",
    "Health Sciences Professions, Dean's Office	",
    "$40,250.00"],

    ["Fernow	",
    "Matthew	",
    "Application Software Developer	",
    "Information Technology - WUSOC	",
    "$65,377.00"],

    ["Filaccio	",
    "Angelo	",
    "Assistant Manager	",
    "Culinary Services	",
    "$40,000.00"],

    ["Fiorelli	",
    "Stephanie	",
    "Communication Manager	",
    "VP For Student Affairs	",
    "$42,000.00"],

    ["Fisher	",
    "Amanda	",
    "Administrative Services Associate, English Language Improvement Program	",
    "Linguistics	",
    "$29,868.80"],

    ["Foley	",
    "Mark	",
    "Technology Commercialization Manager	",
    "Technology Transfer Office	",
    "$86,438.00"],

    ["Fox	",
    "Rebecca	",
    "Administrative Specialist	",
    "E W Scripps Schl of Journalism	",
    "$42,016.00"],

    ["Fox	",
    "Daisy	",
    "N/A	",
    "Nursing	",
    "$56,195.00",],

    ["Fox	",
    "Dennis	",
    "N/A	",
    "Theater	",
    "$47,465.00"],

    ["Fox	",
    "James	",
    "N/A	",
    "English	",
    "$42,184.00"],

    ["Fryman	",
    "Jana	",
    "Assistant Director of Residence Life	",
    "Residence Life, Director's Office	",
    "$53,308.00"],

    ["Fuller	",
    "John	",
    "Sous Chef	",
    "Culinary Services	",
    "$45,955.00"],
    
// G ---------------------------------------------------------------------------
    ["Galbreath	",
    "Robert	",
    "Associate Professor	",
    "Health and Human Services-Eastern	",
    "$75,892.00"],

    ["Giannandrea	",
    "Beatrice	",
    "Associate Professor	",
    "Arts and Sciences-Zanesville	",
    "$71,731.00"],

    ["Gibson	",
    "Andrea	",
    "Special Assistant to the VP/Director of Research	",
    "Research Communications	",
    "$78,087.00"],

    ["Gilkey	",
    "Joseph	",
    "Technical Coordinator	",
    "VP For Student Affairs	",
    "$36,000.00"],

    ["Gillogly	",
    "Sherry	",
    "Department Administrator	",
    "History	",
    "$54,803.00"],

    ["Gist	",
    "Willie	",
    "O'Bleness Professor of Accountancy	",
    "School Of Accountancy	",
    "$150,266.00"],

    ["Gore	",
    "Laurence Robert	",
    "N/A	",
    "Pyschology	",
    "$59,000.00"],

    ["Gossage	",
    "Aaron	",
    "Sous Chef	",
    "Culinary Services	",
    "$45,955.00"],

    ["Gradin	",
    "Sherrie	",
    "Professor	",
    "English	",
    "$126,305.00"],

    ["Graham	",
    "Amanda	",
    "Executive Assistant	",
    "Office of Diversity and Inclusion	",
    "$39,894.40"],

    ["Graham	",
    "Zoe",
    "SEO Marketing Specialist	",
    "Health Sciences Professions, Dean's Office	",
    "$49,364.00"],

    ["Graves	",
    "Erin	",
    "Procurement Senior Specialist	",
    "Scripps College of Communication-Dean's Ofc	",
    "$37,793.60"],

    ["Greenwald	",
    "Marilyn	",
    "Professor	",
    "E W Scripps Schl of Journalism	",
    "$121,780.00"],

    ["Grenert	",
    "Joseph	",
    "Communications Specialist 2: Marketing Communications	",
    "COM-Communication	",
    "$58,814.00"],

    ["Griffitts	",
    "Tara	",
    "Manager of Communication and Academic Relations",	
    "Admissions	",
    "$45,899.00"],

    ["Grimaldi	",
    "Shirina	",
    "Administrative Services Assistant	",
    "Culinary Services	",
    "$23,649.60"],

    ["Grueser	",
    "Barbara	",
    "Administrative Services Associate	",
    "English	",
    "$44,220.80"],

    ["Gunderson	",
    "Maryann	",
    "N/A	",
    "Management	",
    "$55,000.00"],

// H ---------------------------------------------------------------------------
    ["Hajivandi	",
    "Anita	",
    "Assistant Manager	",
    "Culinary Services	",
    "$40,000.00"],

    ["Haney	",
    "Stacy	",
    "Support Services Specialist	",
    "Auxiliaries	",
    "$59,520.00"],

    ["Harmon	",
    "Janelle	",
    "Department Administrator	",
    "Modern Languages	",
    "$57,657.00"],

    ["Harmount	",
    "Jamie Elanie	",
    "N/A	",
    "Education	",
    "$67,135.00"],

    ["Harris	",
    "James	",
    "Assistant Director of Marketing and Communications	",
    "Business, Dean's Office	",
    "$58,170.00"],

    ["Harrison	",
    "Barbara	",
    "Assistant Director, Off-Campus Living	",
    "Business and Residence Services	",
    "$67,754.00"],

    ["Hart	",
    "Chloe	",
    "Assistant Events Director	",
    "Business, Dean's Office	",
    "$49,965.00"],

    ["Hatch	",
    "Laurie	",
    "Professor	",
    "Sociology and Anthropology	",
    "$120,867.00"],

    ["Hatfield	",
    "Sally	",
    "N/A	",
    "OPIE	",
    "$65,615.00"],

    ["Haughey	",
    "Cara	",
    "Director, Annual Giving	",
    "Advancement Services	",
    "$51,258.00"],

    ["Henderson	",
    "Deborah	",
    "Professor	",
    "Nursing - Athens	",
    "$180,793.00"],

    ["Henderson	",
    "Debra	",
    "Associate Professor	",
    "Sociology and Anthropology	",
    "$86,531.00"],

    ["Hibbitt	",
    "Alexandra	",
    "Professor	",
    "Art	",
    "$81,540.00"],

    ["Hicks	",
    "Christopher	",
    "Library Support Associate	",
    "Library-Chillicothe	",
    "$32,177.60"],

    ["Higgins	",
    "Joseph	",
    "Writer	",
    "Health Sciences Professions, Dean's Office	",
    "$44,656.00"],

    ["Hille	",
    "Aaron		",
    "N/A",
    "OPIE	",
    "$69,577.00"],

    ["Hoag	",
    "John	",
    "Associate Professor	",
    "School of Information & Telecommunication Systems	",
    "$107,762.00"],

    ["Hodson	",
    "Thomas	",
    "Associate Professor	",
    "WOUB Center for Public Media	",
    "$136,458.00"],

    ["Holman	",
    "Matthew Martin		",
    "N/A",
    "English	",
    "$44,017.00"],

    ["Holt	",
    "Mara	",
    "Professor	",
    "English	",
    "$97,922.00"],

    ["Horvath	",
    "Carrie	",
    "Business Manager	",
    "Arts and Sciences, Dean's Office	",
    "$71,244.00"],

    ["Hounshell	",
    "Alison		",
    "N/A",
    "OPIE	",
    "$68,285.00"],

    ["Huang	",
    "Steven	",
    "Assoc Professor",	
    "Music	",
    "$70,682.00"],

    ["Humbert	",
    "Jeremy	",
    "Administrative Services Assistant	",
    "Testing Administration	",
    "$26,624.00"],

    ["Huq	",
    "Faizul	",
    "Professor	",
    "Management Systems	",
    "$156,699.00"],

    ["Hutchinson	",
    "Theodore	",
    "Associate Professor	",
    "Educational Studies	",
    "$78,879.00"],

    ["Huynh	",
    "Dinh	",
    "Professor	",
    "Mathematics	",
    "$91,242.00"],

    ["Hysell	",
    "Brant	",
    "Technical Coordinator	",
    "VP For Student Affairs	",
    "$36,000.00"],
    
// I ---------------------------------------------------------------------------
    
    
// J ---------------------------------------------------------------------------
    ["Jago	",
    "Susan	",
    "Director of Payments	",
    "Accounts Payable	",
    "$87,138.00"],

    ["Janson	",
    "Gregory	",
    "Associate Professor	",
    "Dept of Social and Public Health	",
    "$84,193.00"],

    ["Jones	",
    "Mary	",
    "Associate Director, Culinary Services	",
    "Culinary Services	",
    "$117,137.00"],

    ["Jones	",
    "Elizabeth	",
    "Assistant Dean for Outreach and Engagement	",
    "Health Sciences Professions, Dean's Office	",
    "$85,309.00"],

    ["Jones	",
    "Christina	",
    "N/A	",
    "OPIE	",
    "$65,681.00"],

    ["Judd	",
    "Robert	",
    "Professor	",
    "Industrial and Systems Engineering	",
    "$128,320.41"],

    ["Julia	",
    "Goettge	",
    "Administrative Specialist	",
    "Physics and Astronomy	",
    "$41,891.20"],
    
// K ---------------------------------------------------------------------------
    ["Kaaz	",
    "Wendy	",
    "Department Administrator",	
    "Biological Sciences	",
    "$75,000.00"],

    ["Keesey	",
    "Karen	",
    "Administrative Services Associate	",
    "Biological Sciences	",
    "$34,798.40"],

    ["Keffer	",
    "Kim	",
    "N/A	",
    "University College	",
    "$63,353.00"],

    ["Keller	",
    "Erik	",
    "Executive Chef	",
    "Culinary Services	",
    "$71,761.00"],

    ["Kelley	",
    "Mary Jane	",
    "Professor	",
    "Modern Languages	",
    "$102,901.00"],

    ["Kendrick	",
    "Justin	",
    "Administrative Specialist	",
    "Modern Languages	",
    "$34,340.80"],

    ["Khurshid	",
    "Carolyn	",
    "Department Administrator	",
    "Chemistry and Biochemistry	",
    "$58,522.00"],

    ["Kieliszewski	",
    "Marcia	",
    "Professor	",
    "Biochemistry	",
    "$121,895.00"],

    ["Kim	",
    "Sang-Soo	",
    "Associate Professor	",
    "Civil Engineering	",
    "$93,768.00"],

    ["King	",
    "Daniel	",
    "Writer	",
    "Fine Arts, Dean's Office	",
    "$43,502.00"],

    ["King	",
    "Paul	",
    "N/A	",
    "PHYS	",
    "$85,547.00"],

    ["Kline	",
    "Daniel	",
    "N/A	",
    "English	",
    "$52,700.00"],

    ["Koons	",
    "Terry	",
    "Associate Director	",
    "Health Promotion	",
    "$68,290.00"],

    ["Kraft	",
    "Frank	",
    "Professor	",
    "Mechanical Engineering	",
    "$119,199.00"],

    ["Kruse	",
    "Hans	",
    "Professor	",
    "School of Information & Telecommunication Systems	",
    "$144,292.00"],
    
// L ---------------------------------------------------------------------------
    ["Lach	",
    "Laurie	",
    "Director of Development and External Affairs	",
    "Lancaster Dean's Office	",
    "$76,411.00"],

    ["Lamb	",
    "Joseph	",
    "Assoc Professor	",
    "Fine Arts, Dean's Office	",
    "$117,994.00"],

    ["Lancaster	",
    "Lynne	",
    "Professor	",
    "Classics and World Religions	",
    "$100,931.00"],

    ["Large	",
    "Kristina	",
    "Interactive Web & Communication Designer	",
    "INSTRUCTIONAL INNOVATION	",
    "$45,674.00"],

    ["Larson	",
    "Laura	",
    "Professor	",
    "Art	",
    "$79,769.00"],

    ["Larson	",
    "William	",
    "Associate Professor",	
    "Educational Studies	",
    "$81,940.00"],

    ["Lascar	",
    "Amado	",
    "Associate Professor	",
    "Modern Languages	",
    "$68,277.00"],

    ["Lawless	",
    "Rochelle	",
    "Administrative Specialist	",
    "Political Science	",
    "$52,124.80"],

    ["Leatherwood	",
    "Maria	",
    "Academic Advisor	",
    "Scripps College of Communication-Dean's Ofc	",
    "$43,000.00"],

    ["Lee	",
    "Sunggyu	",
    "Professor	",
    "Chemical and Biomolecular Engineering	",
    "$214,373.00"],

    ["Lee	",
    "Joseph	",
    "N/A	",
    "ELIP	",
    "$81,970.00"],

    ["Leite	",
    "Randall	",
    "Assoc Professor	",
    "Health Sciences Professions, Dean's Office	",
    "$192,027.00"],

    ["Lewis	",
    "Marsha	",
    "Associate Professor	",
    "Voinovich Schl - Bldg 21	",
    "$157,043.00"],

    ["Lima	",
    "Edna	",
    "N/A	",
    "ELIP	",
    "$71,476.00"],

    ["Lincoln",	
    "Michael	",
    "Professor	",
    "Theater	",
    "$108,649.00"],

    ["Lindner	",
    "Kyle	",
    "Designer, University Advancement Communication and Marketing	",
    "VP University Advancement	",
    "$39,077.00"],

    ["Lipscomb	",
    "Erica	",
    "Associate Director, Advancement Events	",
    "Advancement Services	",
    "$60,522.00"],

    ["Logue	",
    "Sarah	",
    "Director of Student Recruitment and Communication	",
    "Scripps College of Communication-Dean's Ofc	",
    "$58,882.00"],

    ["Long	",
    "Cecily	",
    "N/A	",
    "OPIE	",
    "$62,140.00"],

    ["Lopez	",
    "Dina	",
    "Professor	",
    "Geological Sciences	",
    "$115,487.00"],

    ["Loucks	",
    "Anne	",
    "Professor	",
    "Biological Sciences	",
    "$137,565.00"],

    ["Lovins	",
    "Nicole	",
    "Assistant Director of Marketing and Design	",
    "Division of Student Affairs Marketing	",
    "$51,749.00"],

    ["Lucas	",
    "Sonya	",
    "Administrative Services Associate (Testing Services Associate)	",
    "Testing Administration	",
    "$35,193.60"],

    ["Lucas	",
    "Mark	",
    "N/A	",
    "PHYS	",
    "$113,659.00"],
    
// M ---------------------------------------------------------------------------
    ["Malloy	",
    "Patricia	",
    "Administrative Specialist	",
    "Geography	",
    "$40,352.00"],

    ["Marciniak	",
    "Katarzyna	",
    "Professor	",
    "English	",
    "$88,125.00"],

    ["Marling	",
    "Cynthia	",
    "Associate Professor	",
    "Electrical Engineering and Computer Science",	
    "$107,116.00"],

    ["Marsh	",
    "Corbin	",
    "Assistant Director of Programming	",
    "Campus Involvement Ctr	",
    "$37,525.00"],

    ["Masterson	",
    "Julia	",
    "Administrative Specialist	",
    "Linguistics	",
    "$35,401.60"],

    ["Matson	",
    "Tamara	",
    "Administrative Services Assistant	",
    "Mathematics	",
    "$28,849.60"],

    ["Mattley	",
    "Christine	",
    "Associate Professor	",
    "Sociology and Anthropology	",
    "$122,276.00"],

    ["Mauzy	",
    "George	",
    "Multimedia Content Specialist	",
    "University Communications and Marketing	",
    "$67,214.00"],

    ["Mayo	",
    "Walter Wright	",
    "N/A	",
    "Math	",
    "$59,104.00"],

    ["McCoy	",
    "Brian	",
    "Administrative Specialist	",
    "Mechanical Engineering	",
    "$44,345.60"],

    ["McCoy	",
    "Patrick	",
    "N/A	",
    "Fine Arts	",
    "$68,768.00"],

    ["McDaid	",
    "Marissa	",
    "Associate Director of Communications	",
    "Engineering and Technology, Dean's Office	",
    "$46,460.00"],

    ["McDaniel	",
    "Drewrey	",
    "Professor, Telecommunications	",
    "Schl of Media Arts & Studies	",
    "$153,320.00"],

    ["McDaniel	",
    "Jeffrey	",
    "University Custodial Services Manager	",
    "Custodial Services	",
    "$51,152.00"],

    ["McDowell	",
    "Sarah	",
    "Art Director, Senior Designer	",
    "ADVANCEMENT COMMUNICATIONS & MARKETING	",
    "$68,594.00"],

    ["McFadden	",
    "Victoria	",
    "Assistant Director, Advancement Events	",
    "Advancement Services	",
    "$47,743.00"],

    ["McGrew	",
    "Diana	",
    "Director of Purchasing	",
    "Procurement Services	",
    "$89,890.00"],

    ["McKinley	",
    "Kristina	",
    "Administrative Services Associate	",
    "School of Communication Studies	",
    "$31,990.40"],

    ["McManus	",
    "Charlotte	",
    "Associate Professor	",
    "Nursing-Chillicothe	",
    "$71,004.00"],

    ["Meale	",
    "Anthony	",
    "Writer	",
    "Education, Dean's Office",	
    "$31,200.00"],

    ["Mekeel	",
    "Lance Arthur	",
    "N/A	",
    "Communication Studies & Theater	",
    "$55,824.00"],

    ["Michael	",
    "Ethan	",
    "Assistant Manager, Zone Maintenance	",
    "Facilities Management	",
    "$59,459.00"],

    ["Miklitsch	",
    "Robert	",
    "Professor	",
    "English	",
    "$99,273.00"],

    ["Miller	",
    "Rita	",
    "Records Management Associate	",
    "Psychology	",
    "$38,584.00"],

    ["Minar	",
    "Scott	",
    "Professor, English",	
    "Arts and Sciences-Lancaster",
    "$91,219.00"],

    ["Mitchell	",
    "Joanna	",
    "N/A	",
    "MODL	",
    "$74,237.00"],

    ["Mohr	",
    "Neal	",
    "Assistant Director, Digital Communication	",
    "Advancement Services	",
    "$39,506.00"],

    ["Moline	",
    "Amanda	",
    "Assistant Director of Marketing & Design	",
    "VP For Student Affairs	",
    "$51,242.00"],

    ["Montalto	",
    "Robert	",
    "Accompanist	",
    "School of Dance, Film & Theater	",
    "$14,913.60"],

    ["Moore	",
    "Dinty	",
    "Professor	",
    "English	",
    "$101,436.00"],

    ["Moore	",
    "Donald	",
    "Associate Professor	",
    "Electronic Media-Southern	",
    "$73,118.00"],

    ["Moran	",
    "Barbara	",
    "Administrative Specialist	",
    "MCCLURE SCHOOL	",
    "$51,771.20"],

    ["Morant	",
    "Lavern	",
    "Assistant Director of Residence Life	",
    "Residence Life, Director's Office	",
    "$51,300.00"],

    ["Morris	",
    "Jeremy	",
    "N/A	",
    "PHIL	",
    "$82,298.00"],

    ["Morrison	",
    "Anne	",
    "Administrative Specialist	",
    "Psychology	",
    "$39,499.20"],

    ["Mullins	",
    "Julia	",
    "Records Management Senior Specialist	",
    "Engineering and Technology, Dean's Office	",
    "$42,848.00"],

    ["Mullins	",
    "Heidi	",
    "Director of Clinical Experiences",	
    "Student Teaching-Education	",
    "$74,396.00"],

    ["Murphy	",
    "Patrick Joseph	",
    "Chief External Relations Officer	",
    "COM-Dean's Office	",
    "$123,018.00"],

    ["Myers	",
    "Jean	",
    "Administrative Services Associate	",
    "Psychology	",
    "$30,784.00"],

    ["Myers	",
    "Bryan	",
    "Advancement Services Coordinator	",
    "Advancement Services	",
    "$56,389.00"],

    ["Mylett	",
    "Daniel	",
    "Designer, University Advancement Communication and Marketing	",
    "ADVANCEMENT COMMUNICATIONS & MARKETING	",
    "$37,000.00"],
    
// N ---------------------------------------------------------------------------
    ["Nadon	",
    "Gregory	",
    "Associate Professor	",
    "Geological Sciences",	
    "$92,662.00"],

    ["Nelson	",
    "Brenda	",
    "Administrative Specialist	",
    "History	",
    "$40,996.80"],

    ["Nelson	",
    "Jenny	",
    "Associate Professor	",
    "Schl of Media Arts & Studies",	
    "$82,291.00"],

    ["Nelson	",
    "Rosanna	",
    "Quality Assurance/HACCP Manager",	
    "Culinary Services	",
    "$58,744.00"],

    ["Nichols	",
    "Treva	",
    "Accounting Support Specialist	",
    "Theater	",
    "$19,593.60"],

    ["Nighswander	",
    "Marcia	",
    "Professor	",
    "Schl of Visual Communication	",
    "$112,549.00"],

    ["Nobles	",
    "John	",
    "N/A	",
    "Management	",
    "$120,532.00"],

    ["Nutter	",
    "Penny	",
    "Administrative Specialist	",
    "Philosophy	",
    "$46,488.00"],
    
// O ---------------------------------------------------------------------------
    ["O'Brien",	
    "Marcy	",
    "Administrative Services Assistant	",
    "Student Affairs-Education	",
    "$35,089.60"],

    ["O'Malley	",
    "Sean	",
    "IT Communications Manager	",
    "Information Technology - WUSOC	",
    "$87,290.00"],

    ["Osetrike",	
    "Arthur	",
    "N/A	",
    "ELIP	",
    "$30,037.00"],

    ["Ottley	",
    "Jennifer	",
    "Associate Professor	",
    "Teacher Education	",
    "$80,097.00"],
    
// P ---------------------------------------------------------------------------
    ["Panek	",
    "Thomas	",
    "N/A	",
    "Business Management Technology	",
    "$57,853.00"],

    ["Park	",
    "Hyo Jung	",
    "N/A	",
    "ELIP	",
    "$71,680.00"],

    ["Parrot	",
    "Benjamin	",
    "N/A	",
    "MODL	",
    "$72,220.00"],

    ["Patrick	",
    "Rachel	",
    "Project Manager/Business Analyst	",
    "Assoc VP for Finance & Admin	",
    "$76,886.00"],

    ["Paulins	",
    "Virginia	",
    "Professor	",
    "Department of Human and Consumer Sciences	",
    "$145,004.00"],

    ["Pero	",
    "Kelly	",
    "Department Administrator	",
    "Psychology	",
    "$69,465.00"],

    ["Perry	",
    "Patsy	",
    "Administrative Services Associate	",
    "Testing Administration	",
    "$30,160.00"],

    ["Peters	",
    "Rena	",
    "Administrative Specialist	",
    "OPIE	",
    "$46,737.60"],

    ["Peters	",
    "Karen	",
    "Administrative Specialist	",
    "Scripps College of Communication-Dean's Ofc	",
    "$40,331.20"],

    ["Phillips	",
    "James	",
    "Communication Specialist 2: Earned & Social Media",	
    "COM-Communication	",
    "$47,760.00"],

    ["Pidcock	",
    "Leonard	",
    "Director of Professional Experiences	",
    "Engineering and Technology, Dean's Office	",
    "$65,604.00"],

    ["Pierre	",
    "Anna	",
    "Manager of Communication and Academic Relations	",
    "Admissions	",
    "$50,501.00"],

    ["Pina	",
    "Shai	",
    "Administrative Specialist	",
    "Women's & Gender Studies	",
    "$17,170.40"],

    ["Pittman	",
    "Daniel	",
    "Associate Director of Communications",	
    "Health Sciences Professions, Dean's Office	",
    "$68,160.00"],

    ["Pollard	",
    "Connie	",
    "Department Administrator, English, Classics and World Religions, and Philosophy	",
    "English	",
    "$78,138.00"],

    ["Potratz	",
    "Christopher",	
    "N/A	",
    "Chemistry	",
    "$55,311.00"],

    ["Price	",
    "Kevin	",
    "Education and Media Supervisor	",
    "WOUB Center for Public Media	",
    "$50,901.00"],

    ["Pritchett	",
    "Chett	",
    "Associate Director, External Relations	",
    "COM-Medical Development/Alumni Affairs	",
    "$58,928.00"],
    
// Q ---------------------------------------------------------------------------
    
    
// R ---------------------------------------------------------------------------
    ["Raines	",
    "Michelle	",
    "Administrative Specialist	",
    "Economics	",
    "$45,489.60"],

    ["Rainey	",
    "Teresa	",
    "Administrative Services Associate	",
    "Multi-Cultural Programs	",
    "$33,966.40"],

    ["Rawlins	",
    "William	",
    "Stocker Professor	",
    "School of Communication Studies	",
    "$128,202.00"],

    ["Redefer	",
    "Jefferey	",
    "Associate Professor	",
    "Schl of Media Arts & Studies	",
    "$92,855.00"],

    ["Reghetti-Feyler	",
    "Christine	",
    "Assistant Director	",
    "Residence Life, Director's Office	",
    "$63,353.00"],

    ["Reichley	",
    "Justine	",
    "Assistant Director Housing and Residence Life, Student Engagement and Summer Experiences",	
    "Housing	",
    "$40,400.00"],

    ["Reynolds	",
    "Anthony	",
    "N/A	",
    "Sports Admin	",
    "$65,650.00"],

    ["Richardson	",
    "Hugh	",
    "Professor	",
    "Chemistry and Biochemistry	",
    "$96,135.00"],

    ["Ridenour	",
    "Jenny	",
    "Administrative Specialist	",
    "Molecular and Cellular Biology	",
    "$25,755.60"],

    ["Riggs	",
    "Kathleen	",
    "Administrative Services Associate	",
    "Event Services	",
    "$32,448.00"],

    ["Riggs	",
    "Thomas	",
    "Graduate Program Administrator	",
    "Chemical and Biomolecular Engineering	",
    "$16,781.44"],

    ["Risler	",
    "Laura	",
    "Director of Special Projects and Data Analysis	",
    "Provost Office	",
    "$66,933.00"],

    ["Roberson	",
    "Roberta	",
    "N/A	",
    "SOAN	",
    "$69,476.00"],

    ["Roberts	",
    "Julianna	",
    "Academic Records and Athletic Eligibility Coordinator	",
    "Registrar's Office	",
    "$47,078.00"],

    ["Robson	",
    "Tracy	",
    "Administrative Services Associate	",
    "Physics and Astronomy	",
    "$40,081.60"],

    ["Rosser	",
    "Jill	",
    "Professor	",
    "English	",
    "$87,011.00"],

    ["Roush	",
    "Sarah	",
    "Media Specialist	",
    "Scripps College of Communication-Dean's Ofc	",
    "$47,977.00"],

    ["Ryan	",
    "Timothy	",
    "Professor	",
    "Dept of Social and Public Health	",
    "$106,375.00"],
    
// S ---------------------------------------------------------------------------
    ["Savage	",
    "Charles",	
    "N/A	",
    "Music	",
    "$55,201.00"],

    ["Scarmack	",
    "Ralph	",
    "Assistant Manager - Retail Operations",	
    "Culinary Services - WGMD	",
    "$40,784.00"],

    ["Schleter	",
    "David	",
    "Biological and Chemical Safety Officer	",
    "Risk Management & Safety	",
    "$58,472.00"],

    ["Schmehl	",
    "Rebecca	",
    "Assocciate Professor	",
    "Schl of Visual Communication	",
    "$84,526.00"],

    ["Schodzinski	",
    "E J	",
    "Director of External Relations	",
    "Eastern Campus Dean's Office	",
    "$82,137.00"],

    ["Schwartz	",
    "Louis-Georges	",
    "Associate Professor	",
    "Film	",
    "$70,548.00"],

    ["Schwartz	",
    "Regina	",
    "Senior Director of Communication and Marketing	",
    "Health Sciences Professions, Dean's Office	",
    "$80,983.00"],

    ["Seckinger	",
    "Holly	",
    "Associate Director of Alumni Engagement	",
    "CAREER AND STUDENT SUCCESS CTR	",
    "$76,886.00"],

    ["Shakespear	",
    "Audrey	",
    "Woodshop and Sculpture Technician	",
    "School of Art & Design	",
    "$44,954.00"],

    ["Sharpe	",
    "Nina	",
    "Senior Department Administrator	",
    "Political Science	",
    "$66,128.00"],

    ["Sheets	",
    "Cheri	",
    "Administrative Specialist	",
    "Geological Sciences	",
    "$41,995.20"],

    ["Shevchenko	",
    "Mila	",
    "N/A	",
    "MODL	",
    "$72,096.00"],

    ["Shirvani	",
    "Sheida	",
    "Professor	",
    "Communication-Zanesville	",
    "$97,135.00"],

    ["Shooner	",
    "Peter	",
    "Associate Director, Content	",
    "Advancement Services	",
    "$61,506.00"],

    ["Siebrits	",
    "Helene	",
    "Associate Professor	",
    "School of Dance, Film & Theater	",
    "$65,550.00"],

    ["Simpson	",
    "Isaac	",
    "Accounting Support Associate	",
    "Campus Involvement Center	",
    "$26,499.20"],

    ["Sindelar	",
    "Betty	",
    "Assoc Professor	",
    "Physical Therapy	",
    "$132,978.00"],

    ["Slusser",	
    "Kailee	",
    "Design and Web UX Manager	",
    "VP For Student Affairs	",
    "$44,493.00"],

    ["Smith	",
    "Teresa	",
    "Administrative Services Associate	",
    "Testing Administration	",
    "$31,532.80"],

    ["Smith	",
    "Charles	",
    "Professor	",
    "Theater	",
    "$108,386.00"],

    ["Smith	",
    "Misti	",
    "Development Coordinator	",
    "Engineering and Technology, Dean's Office	",
    "$47,168.00"],

    ["Snyder	",
    "Kathryn",	
    "Assistant Director, Community Standards and Student Responsibility	",
    "Community Standards & Student Responsibility	",
    "$45,000.00"],

    ["Solomon	",
    "Tamala	",
    "Senior Director, Alumni Relations & External Affairs	",
    "Education, Dean's Office	",
    "$67,847.00"],

    ["Sparks	",
    "Scott	",
    "Professor	",
    "Teacher Education	",
    "$103,563.00"],

    ["Spaulding	",
    "Candice	",
    "Administrative Services Associate	",
    "Physics and Astronomy	",
    "$31,928.00"],

    ["Spjeldnes	",
    "Solveig	",
    "Associate Professor	",
    "Social Work	",
    "$77,539.00"],

    ["Stanford	",
    "Aaron	",
    "Manager, Fire Safety	",
    "Environmental Health & Safety	",
    "$56,383.00"],

    ["Starcher	",
    "Mary	",
    "Administrative Services Assistant	",
    "Education, Dean's Office	",
    "$30,430.40"],

    ["Stevens	",
    "Jon	",
    "University Custodial Services Manager	",
    "Custodial Services	",
    "$51,152.00"],

    ["Stewart	",
    "Robert	",
    "Professor	",
    "E W Scripps Schl of Journalism	",
    "$139,620.00"],

    ["Stewart	",
    "Jack	",
    "Network Engineer III	",
    "IT Networks	",
    "$77,894.00"],

    ["Stottlemyer",	
    "Ashley	",
    "Photographer/Designer	",
    "Engineering and Technology, Dean's Office	",
    "$47,236.00"],

    ["Stowe	",
    "John	",
    "Professor	",
    "Finance	",
    "$155,012.00"],
    
// T ---------------------------------------------------------------------------
    ["Tabor",	
    "Kara	",
    "Administrative Services Associate	",
    "Sociology and Anthropology	",
    "$30,784.00"],

    ["Taylor	",
    "Jimmy	",
    "Associate Professor	",
    "Arts and Sciences-Zanesville	",
    "$72,129.00"],

    ["Thomas	",
    "David	",
    "Professor	",
    "Film	",
    "$112,553.00"],

    ["Thompson	",
    "Elizabeth",	
    "N/A	",
    "ENGL	",
    "$80,458.00"],

    ["Thomson",	
    "Matthew",	
    "Program Manager of CoLab	",
    "MANAGEMENT	",
    "$52,260.00"],

    ["Timpson",	
    "Jason	",
    "Assistant Director of Residence Life",	
    "Residence Life, Director's Office	",
    "$52,000.00"],

    ["Trese	",
    "Arthur	",
    "Associate Professor	",
    "Environmental and Plant Biology	",
    "$97,547.00"],

    ["Truax	",
    "Jennifer	",
    "University Custodial Services Manager",	
    "Custodial Services	",
    "$43,500.00"],

    ["Tuttle	",
    "Sara	",
    "Real Estate Coordinator	",
    "VP For Finance and Administration	",
    "$48,000.00"],
    
// U ---------------------------------------------------------------------------
    ["Urano	",
    "David	",
    "Director, Video & Photography Services	",
    "University Communications and Marketing",	
    "$71,792.00"],

    ["Uzuegbunam	",
    "Ikenna	",
    "Associate Professor, Strategic Management, International Business, and Entrepreneurship",	
    "Management Systems	",
    "$150,107.00"],
    
// V ---------------------------------------------------------------------------
    ["Vandeman	",
    "Nancy	",
    "Accounting Support Specialist	",
    "English	",
    "$34,798.40"],

    ["Vargo	",
    "Connie	",
    "Department Administrator, Environmental and Plant Biology	",
    "Environmental and Plant Biology	",
    "$49,891.00"],

    ["Vickers	",
    "Timothy	",
    "Associate Director	",
    "INSTRUCTIONAL INNOVATION	",
    "$71,732.00"],

    ["Voltz	",
    "Holly	",
    "Coordinator of Marketing and Public Relations	",
    "Zanesville Dean's Office	",
    "$52,773.00"],
    
// W ---------------------------------------------------------------------------
    ["Wagner	",
    "Darci Dawn	",
    "N/A	",
    "Applied Management	",
    "$53,092.00"],

    ["Walburn	",
    "Terry	",
    "University Custodial Services Manager	",
    "Custodial Services	",
    "$41,526.00"],

    ["Walker	",
    "Liesta	",
    "N/A	",
    "University College	",
    "$49,890.00"],

    ["Wallace	",
    "Lara	",
    "N/A	",
    "ELIP	",
    "$87,051.00"],

    ["Wang	",
    "Qing	",
    "Multimedia Producer	",
    "Engineering Technology & Management	",
    "$30,153.76"],

    ["Warner	",
    "Cory	",
    "Associate Director of Operations	",
    "Health Sciences Professions, Dean's Office	",
    "$65,036.00"],

    ["Watts	",
    "Alan	",
    "Director of Laboratory & Radiation Safety	",
    "Risk Management & Safety	",
    "$100,066.00"],

    ["Weisenbach	",
    "Luanne	",
    "Records Management Senior Specialist	",
    "OII Business Services	",
    "$40,851.20"],

    ["Weiss	",
    "Linda	",
    "Marketing & Design Manager	",
    "Division of Student Affairs Marketing	",
    "$48,182.00"],

    ["Werger	",
    "Arthur	",
    "Professor	",
    "Art	",
    "$103,840.00"],

    ["Wetzel	",
    "Richard	",
    "Professor, Music ",
    "History & Lit	Music",	
    "$116,597.00"],

    ["Whitt	",
    "Laura	",
    "Senior Director, Professional Outreach and Alumni Affairs",	
    "COM-Osteopathic Manipulative Medicine	",
    "$92,572.00"],

    ["Wickham	",
    "Michael	",
    "Assistant Registrar for Registration	",
    "Registrar's Office	",
    "$68,753.00"],

    ["Wilkinson	",
    "Kathaleen	",
    "Executive Assistant	",
    "Arts and Sciences, Dean's Office	",
    "$39,520.00"],

    ["Wilson	",
    "Brittany	",
    "Catering Coordinator",	
    "Culinary Services	",
    "$46,568.00"],

    ["Windsor Green	",
    "Ann	",
    "Administrative Services Associate	",
    "WOUB Center for Public Media	",
    "$41,787.20"],

    ["Winstead	",
    "Kenneth	",
    "Senior Director of Development, Athletics/Senior Associate Athletics Director for Development	",
    "Development	",
    "$108,369.00"],

    ["Witham	",
    "Kevin	",
    "Director of Recruitment and Outreach	",
    "Admissions	",
    "$100,312.00"],

    ["Wolfe	",
    "Christine	",
    "Assoc Professor	",
    "Business Technology-Lancaster	",
    "$85,673.00"],

    ["Woodall	",
    "Walter	",
    "N/A	",
    "MODL	",
    "$80,873.00"],

    ["Woodward	",
    "Angela	",
    "Assistant Director, Content",	
    "Advancement Services	",
    "$51,359.00"],

    ["Wright	",
    "Barbara	",
    "Administrative Services Associate	",
    "Sch of Applied Health Sciences and Wellness",
    "$35,713.60"],
    
// X ---------------------------------------------------------------------------
    
    
// Y ---------------------------------------------------------------------------
    ["York	",
    "Karen	",
    "University Custodial Services Manager	",
    "Custodial Services	",
    "$50,899.00"],

    ["Yost	",
    "Christine	",
    "N/A	",
    "Accounting	",
    "$97,768.00"],

    ["Young	",
    "Kimberly	",
    "Administrative Services Assistant	",
    "OPIE	",
    "$26,748.80"],

    ["Young	",
    "Lauren	",
    "Administrative Services Assistant	",
    "II Business Services	",
    "$21,432.32"],
    
// Z ---------------------------------------------------------------------------
    ["Zhang	",
    "Da	",
    "Associate Professor	",
    "Computer Science Technology - Lancaster",	
    "$72,458.00"],

    ["Ziff	",
    "Matthew	",
    "Assoc Professor	",
    "Art	",
    "$79,869.00"],

    ["Zulia	",
    "Eleni	",
    "Executive Director, Annual Giving	",
    "Advancement Services	",
    "$86,948.00"]
    

];

$(document).ready(function () {
    $('#example').DataTable({
        data: dataSet,
        "scrollX": true,
        "order": [[4, "desc"]],
        columns: [{
                title: "Last"
            },
            {
                title: "First"
            },
            {
                title: "Title"
            },
            {
                title: "Department"
            },
            {
                title: "Salary"
            }
        ],
        language: {
            searchPlaceholder: "Search records",
            search: "",
        },
        "dom": '<"pull-left"f><"pull-right"l>tip'


    });
});
